name: VSCE Build of VSCode Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install -g vsce
        npm install
        vsce package

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: suricata-intellisense-vscode
        path: |
          *.vsix
